@baseUrl = http://localhost:3333
@token = {{authentication_sign_in.response.body.token}}

###
# @name authentication_sign_in
POST {{baseUrl}}/authentication/sign-in
Content-Type: application/json

{
  "email": "administrador@adacaibs.com",
  "password": "10203040"
}

###

POST {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "user adacaibs",
  "email": "user1@adacaibs.com",
  "role": "EDITOR"
}

###
# @name user_paginate
GET {{baseUrl}}/user/paginate
Content-Type: application/json
Authorization: Bearer {{token}}